openapi: 3.0.1
servers:
  - url: https://api.spotify.com/v1
info:
  title: Spotify Web API
  version: 2021.4.2
  x-apisguru-categories:
    - media
  x-logo:
    url: https://logo-core.clearbit.com/spotify.com
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/sonallux/spotify-web-api/master/spotify-web-api-generator-open-api/spotify-web-api-openapi.yml
      version: "3.0"
  x-providerName: spotify.com
  x-unofficialSpec: true
tags:
  - description: Albums API
    name: category-albums
  - description: Artists API
    name: category-artists
  - description: Browse API
    name: category-browse
  - description: Episodes API
    name: category-episodes
  - description: Follow API
    name: category-follow
  - description: Library API
    name: category-library
  - description: Markets API
    name: category-markets
  - description: Personalization API
    name: category-personalization
  - description: Player API
    name: category-player
  - description: Playlists API
    name: category-playlists
  - description: Search API
    name: category-search
  - description: Shows API
    name: category-shows
  - description: Tracks API
    name: category-tracks
  - description: Users Profile API
    name: category-users-profile
paths:
  /albums:
    get:
      description: Get Spotify catalog information for multiple albums identified by
        their Spotify IDs.
      operationId: endpoint-get-multiple-albums
      security:
        - spotify_auth: []
      summary: Get Multiple Albums
      tags:
        - category-albums
  "/albums/{id}":
    get:
      description: Get Spotify catalog information for a single album.
      operationId: endpoint-get-an-album
      security:
        - spotify_auth: []
      summary: Get an Album
      tags:
        - category-albums
  "/albums/{id}/tracks":
    get:
      description: |-
        Get Spotify catalog information about an album's tracks.
        Optional parameters can be used to limit the number of tracks returned.
      operationId: endpoint-get-an-albums-tracks
      security:
        - spotify_auth: []
      summary: Get an Album's Tracks
      tags:
        - category-albums
  /me/following:
    delete:
      description: Remove the current user as a follower of one or more artists or
        other Spotify users.
      operationId: endpoint-unfollow-artists-users
      security:
        - spotify_auth:
            - user-follow-modify
      summary: Unfollow Artists or Users
      tags:
        - category-follow
    get:
      description: Get the current user's followed artists.
      operationId: endpoint-get-followed
      security:
        - spotify_auth:
            - user-follow-modify
      summary: Get User's Followed Artists
      tags:
        - category-follow
    put:
      description: Add the current user as a follower of one or more artists or other
        Spotify users.
      operationId: endpoint-follow-artists-users
      security:
        - spotify_auth:
            - user-follow-modify
      summary: Follow Artists or Users
      tags:
        - category-follow
  /me/following/contains:
    get:
      description: Check to see if the current user is following one or more artists
        or other Spotify users.
      operationId: endpoint-check-current-user-follows
      security:
        - spotify_auth:
            - user-follow-read
      summary: Get Following State for Artists/Users
      tags:
        - category-follow
  /me/player:
    get:
      description: Get information about the user's current playback state, including
        track or episode, progress, and active device.
      operationId: endpoint-get-information-about-the-users-current-playback
      security:
        - spotify_auth:
            - user-read-playback-state
      summary: Get Information About The User's Current Playback
      tags:
        - category-player
    put:
      description: Transfer playback to a new device and determine if it should start
        playing.
      operationId: endpoint-transfer-a-users-playback
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Transfer a User's Playback
      tags:
        - category-player
  /me/player/currently-playing:
    get:
      description: Get the object currently being played on the user's Spotify account.
      operationId: endpoint-get-the-users-currently-playing-track
      security:
        - spotify_auth:
            - user-read-currently-playing
            - user-read-playback-state
      summary: Get the User's Currently Playing Track
      tags:
        - category-player
  /me/player/devices:
    get:
      description: Get information about a user's available devices.
      operationId: endpoint-get-a-users-available-devices
      security:
        - spotify_auth:
            - user-read-playback-state
      summary: Get a User's Available Devices
      tags:
        - category-player
  /me/player/next:
    post:
      description: Skips to next track in the user's queue.
      operationId: endpoint-skip-users-playback-to-next-track
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Skip User’s Playback To Next Track
      tags:
        - category-player
  /me/player/pause:
    put:
      description: Pause playback on the user's account.
      operationId: endpoint-pause-a-users-playback
      security:
        - spotify_auth: []
      summary: Pause a User's Playback
      tags:
        - category-player
  /me/player/play:
    put:
      description: Start a new context or resume current playback on the user's active
        device.
      operationId: endpoint-start-a-users-playback
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Start/Resume a User's Playback
      tags:
        - category-player
  /me/player/previous:
    post:
      description: Skips to previous track in the user's queue.
      operationId: endpoint-skip-users-playback-to-previous-track
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Skip User’s Playback To Previous Track
      tags:
        - category-player
  /me/player/queue:
    post:
      description: Add an item to the end of the user's current playback queue.
      operationId: endpoint-add-to-queue
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Add an item to queue
      tags:
        - category-player